.DEFAULT_GOAL := task0

task0:
	cd tasks/task0 && python main.py && cd ../..

dop1:
	cd tasks/dop1 && python main.py && cd ../..

dop2:
	cd tasks/dop2 && python main.py && cd ../..

dop3:
	cd tasks/dop3 && python main.py && cd ../..

dop4:
	cd tasks/dop4 && python main.py && cd ../..

repl:
	python
