DROP TABLE development_directions CASCADE;
DROP TABLE appointments CASCADE;
DROP TABLE laboratories CASCADE;
DROP TABLE research_areas CASCADE;
DROP TABLE breaks CASCADE;
DROP TABLE employees CASCADE;
DROP TABLE cylinders CASCADE;
DROP TABLE shaving_foams CASCADE;
DROP TABLE backpacks CASCADE;
DROP TABLE people_actions CASCADE;
DROP TABLE people CASCADE;
DROP TABLE locations CASCADE;
DROP TABLE items CASCADE;
DROP TYPE sex;
DROP TYPE actions;
DROP TYPE brands;
DROP TYPE entity_tables;
DROP DOMAIN uint2;
