/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.itmo.prog.lab3;

import org.junit.Test;
import static org.junit.Assert.*;

public class StoryTest {
    @Test public void appHasAGreeting() {
        Story classUnderTest = new Story();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
