version: '2'
services:
 web:
   image: vulhub/ruby:2.4.1
   command: ruby web.rb -p 8080 -o 0.0.0.0
   working_dir: /usr/src
   volumes:
    - ./web.rb:/usr/src/web.rb
   ports:
    - "8080:8080"

 web-updated-ruby:
   image: ruby:2.4.3
   command: bash -c "bundle install && ruby web.rb -p 8081 -o 0.0.0.0"
   working_dir: /usr/src
   volumes:
    - ./web.rb:/usr/src/web.rb
    - ./Gemfile:/usr/src/Gemfile
   ports:
    - "8081:8081"

 web-with-patch:
   image: vulhub/ruby:2.4.1
   command: ruby web_with_patch.rb -p 8082 -o 0.0.0.0
   working_dir: /usr/src
   volumes:
    - ./ftp_security_patch.rb:/usr/src/ftp_security_patch.rb
    - ./web_with_patch.rb:/usr/src/web_with_patch.rb
   ports:
    - "8082:8082"
